TRAINING_TRIALS: [{level: 4, n_trails: 1}, {level: 5, n_trails: 1}, {level: 6, n_trails: 4}]
EXPERIMENT_TRIALS: [{level: 5, n_trails: 2}, {level: 6, n_trails: 2}]


# time in seconds
CONST_TIME: 0
LEVEL_TIME: 3.5
JITTER_TIME: 1.5

# visual parameters
TEXT_SIZE: 32
VIZ_OFFSET: 50

# clock
## show clock n second before trial end
SHOW_CLOCK: 4
CLOCK_POS: [0, 350]
CLOCK_SIZE: 120

# distractor on/off
DISTRACTORS: False

# answer frame
height: 40
width: 40
click_color: yellow
answer_color: green
lineWidth: 3


feedback_time: 1
wait_after_answer: 0.2