TRAINING_TRIALS: [{level: 3, n_trails: 6}, {level: 4, n_trails: 2}]
START_LEVEL: 3
MAX_REVS: 5
MAX_TRIALS: 70
MIN_LEVEL: 3
MAX_LEVEL: 8

# time in seconds
CONST_TIME: 0
LEVEL_TIME: 3.5
JITTER_TIME: 1.5

# visual parameters
TEXT_SIZE: 32
VIZ_OFFSET: 50

# clock
## show clock n second before trial end
SHOW_CLOCK: 4
CLOCK_POS: [0, 350]
CLOCK_SIZE: 120

# distractor on/off
DISTRACTORS: False
