TRAINING_TRIALS: [{level: 3, n_trails: 5}]
EXPERIMENT_TRIALS: [{level: 3, n_trails: 25}, {level: 4, n_trails: 15},{level: 5, n_trails: 6}, {level: 6, n_trails: 4}]

min_training_acc: 0.3

# time in seconds
CONST_TIME: 7
LEVEL_TIME: 2.5
JITTER_TIME: 1.5

# visual parameters
TEXT_SIZE: 32
VIZ_OFFSET: 65

# clock
## show clock n second before trial end
SHOW_CLOCK: 5
CLOCK_POS: [0, 350]
CLOCK_SIZE: 120

# distractor on/off
DISTRACTORS: True

# answer frame
height: 50
width: 50
click_color: blue
answer_color: green
lineWidth: 3


feedback_time: -1 # for -1 participant have to presses space
wait_after_answer: 0.2

pos_feedb: Odpowiedziałeś poprawnie
neg_feedb: Odpowiedziałeś niepoprawnie. Poprawna odpowiedź jest wyświetlona powyżej.
no_feedb: Nie udzieliłeś odpowiedzi